version: "3"

dotenv:
  - ".env"

tasks:
  dev:
    cmds:
      - "hugo server -D --bind=${HOST_IP} --baseURL=http://${HOST_IP} --port=1313 -d /tmp/mika"
  clean:
    cmds:
      - rm -rf /tmp/mika
      - rm -rf resources
  sync:
    cmds:
      - hugo -d /tmp/mika
      - "rsync -a -I --delete /tmp/mika/ ${TARGET_IP}:/usr/share/nginx/html/"
      - rm -rf /tmp/mika
      - rm -rf ./resources
